name: 'aws-catalog-update-product-action'
description: 'Update parameters of Provisisoned Product in AWS Service Catalog'
author: 'm-jonn'

inputs:
  provisioned-product-region:
    description: 'AWS Region of the provisioned product in AWS Service Catalog'
    required: true
  provisioned-product-id:
    description: 'Id of the provisioned product in AWS Service Catalog'
    required: true
  provisioned-parameters-json:
    description: 'Relative path to json file containing the parameters of the provisioned product in AWS Service Catalog'
    required: false
    default: 'aws-provisioned-parameters.json'

outputs:
  status:
    description: 'Status of the provisioned Product'

runs:
  using: node20
  main: dist/index.js