name: 'aws-catalog-update-product-action'
description: 'Update provisisoned Products on AWS Service Catalog'
author: 'm-jonn'

# Define your inputs here.
inputs:
  aws-region:
    description: 'AWS Region Code for the provisioned Product'
    required: true
  provisioned-product-id:
    description: 'Id of the provisioned Product in AWS Service Catalog'
    required: true

# Define your outputs here.
outputs:
  version:
    description: 'Version of the provisioned Product'

runs:
  using: node20
  main: dist/index.js